# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Workshop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Workshop
  pod 'WatchSync'

  target 'WorkshopTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Workshop WatchKit App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Workshop WatchKit App

end

target 'Workshop WatchKit Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Workshop WatchKit Extension
  pod 'WatchSync'

end
